<a href="https://colab.research.google.com/github/stephleao/wmc-desafio-streaming-churn/blob/main/%5BNina_da_Hora%5D_Probabilidade_e_Amostragem_%7C_Bootcamp_Data_Analytics_2026_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

# 1. CARREGAMENTO DA BASE CORRIGIDO (Adicionado o sep=';')
url = 'https://raw.githubusercontent.com/stephleao/wmc-desafio-streaming-churn/refs/heads/main/clientes.csv'
df = pd.read_csv(url, sep=';')

# Previa do dataframe
df.head()

,cliente_id,idade,tempo_assinatura_meses,frequencia_uso_mensal,regiao,mensalidade,cancelou
0,1,56,30,27,Centro-Oeste,96.03,1
1,2,69,11,2,Norte,91.22,0
2,3,46,58,21,Sul,56.45,0
3,4,32,55,1,Norte,69.61,0
4,5,60,28,28,Sul,42.19,0

In [2]:
'''
Funcao para fazer uma exploracao inicial do df
Retorna informacoes sobre tamanho do df, tipos de dados, total de nulos
e estatisticas descritivas
'''
def explorar_dataframe(df):
  dataframe_info = pd.concat([df.dtypes, df.isna().sum()], axis=1).rename(columns={
    0: 'Tipo de dado',
    1: 'Total de nulos'
  })

  print(f'Tamanho do dataframe: {df.shape[0]} linhas e {df.shape[1]} colunas')
  print('-' * 50 )
  print(f'Linhas duplicadas: {df.duplicated().sum()}')
  print('-' * 50 )
  print('Informações de tipo de dados e total de nulos:\n', dataframe_info)
  print('-' * 50 )
  print('Estatísticas descritivas:\n', df.describe().T)

  if df.select_dtypes(include=['str', 'object']).shape[1] > 0:
    print('-' * 50 )
    print('Estatísticas descritivas para colunas categóricas:\n', df.describe(include=['str', 'object']).T)

  if df.select_dtypes(include=['bool']).shape[1] > 0:
    print('-' * 50 )
    print('% de TRUE em colunas booleanas:\n', df.select_dtypes(include=['bool']).mean() * 100)

explorar_dataframe(df)

Tamanho do dataframe: 200 linhas e 7 colunas
--------------------------------------------------
Linhas duplicadas: 0
--------------------------------------------------
Informações de tipo de dados e total de nulos:
                        Tipo de dado  Total de nulos
cliente_id                    int64               0
idade                         int64               0
tempo_assinatura_meses        int64               0
frequencia_uso_mensal         int64               0
regiao                          str               0
mensalidade                 float64               0
cancelou                      int64               0
--------------------------------------------------
Estatísticas descritivas:
                         count     mean        std    min      25%     50%  \
cliente_id              200.0  100.500  57.879185   1.00  50.7500  100.50
idade                   200.0   45.260  16.040852  18.00  31.7500   45.00
tempo_assinatura_meses  200.0   30.890  17.679102   1.00  16.7500   32.00
frequencia_uso_mensal   200.0   15.980   8.843679   1.00   8.0000   17.00
mensalidade             200.0   59.129  23.318007  21.16  38.8075   57.71
cancelou                200.0    0.280   0.450126   0.00   0.0000    0.00

                           75%     max
cliente_id              150.25  200.00
idade                    59.00   74.00
tempo_assinatura_meses   48.00   59.00
frequencia_uso_mensal    23.00   29.00
mensalidade              79.68   99.98
cancelou                  1.00    1.00
--------------------------------------------------
Estatísticas descritivas para colunas categóricas:
        count unique           top freq
regiao   200      5  Centro-Oeste   47

A exploração inicial mostrou que a coluna `cancelou` está como `int`, mas na realidade é booleana, então pode-se fazer uma conversão.

In [3]:
#Converte a coluna 'cancelou' para booleano
df['cancelou'] = df['cancelou'].astype(bool)

explorar_dataframe(df)

df.head(5)

Tamanho do dataframe: 200 linhas e 7 colunas
--------------------------------------------------
Linhas duplicadas: 0
--------------------------------------------------
Informações de tipo de dados e total de nulos:
                        Tipo de dado  Total de nulos
cliente_id                    int64               0
idade                         int64               0
tempo_assinatura_meses        int64               0
frequencia_uso_mensal         int64               0
regiao                          str               0
mensalidade                 float64               0
cancelou                       bool               0
--------------------------------------------------
Estatísticas descritivas:
                         count     mean        std    min      25%     50%  \
cliente_id              200.0  100.500  57.879185   1.00  50.7500  100.50
idade                   200.0   45.260  16.040852  18.00  31.7500   45.00
tempo_assinatura_meses  200.0   30.890  17.679102   1.00  16.7500   32.00
frequencia_uso_mensal   200.0   15.980   8.843679   1.00   8.0000   17.00
mensalidade             200.0   59.129  23.318007  21.16  38.8075   57.71

                           75%     max
cliente_id              150.25  200.00
idade                    59.00   74.00
tempo_assinatura_meses   48.00   59.00
frequencia_uso_mensal    23.00   29.00
mensalidade              79.68   99.98
--------------------------------------------------
Estatísticas descritivas para colunas categóricas:
        count unique           top freq
regiao   200      5  Centro-Oeste   47
--------------------------------------------------
% de TRUE em colunas booleanas:
 cancelou    28.0
dtype: float64

,cliente_id,idade,tempo_assinatura_meses,frequencia_uso_mensal,regiao,mensalidade,cancelou
0,1,56,30,27,Centro-Oeste,96.03,True
1,2,69,11,2,Norte,91.22,False
2,3,46,58,21,Sul,56.45,False
3,4,32,55,1,Norte,69.61,False
4,5,60,28,28,Sul,42.19,False